### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by pedrost** [JoshTheDerf/prerenderer#30]
Hey guys! I'm trying to prerender some routes (550 actually), I'm getting the error "unable to preload all routes" so I decide to prerender only a few (20), the build it's complete but I keep recieving this kind of message 

`SyntaxError: Unexpected token <`
[https://puu.sh/D0tuW/8bb4e83f85.png](url)
`TypeError: Cannot read property 'bind' of undefined`
[https://puu.sh/D0twe/feba737904.png](url)

Also, this is my webpack config
[https://puu.sh/D0tzi/7b103a152f.png](url)

**Comment by Tofandel** [comment]
This looks like errors inside your routes

I'm guessing trying to load json but receiving an html error or something like this

Screenshots are not accessible anymore (and anyway shouldn't be used to show config and error messages, there is code blocks for this) and this is an old issue so I'll be closing it

Feel free to add some more elements if you still have the issue and I'll reopen
