### ISSUE TITLE
Compatibility with @vue/cli-plugin-pwa

### ISSUE THREAD

**Issue by jaunt** [JoshTheDerf/prerenderer#34]
Hi,

I'm wondering if you have any advice on how I can make modifications such that the pre-rendered files get properly incorporated into the precache-manifest file that workbox creates.  I'm happy to do the work, but some guidance would be greatly appreciated.  My feeling is that the order of operations needs to worked out so that after pre-rendering, the workbox functionality creates the manifest with new hashes for the new route files, and the modified index.html file.  Note:  Using vue-cli-plugin-prerender-spa.  Thanks!

**Comment by jaunt** [comment]
My solution is here, but I've since abandoned pre-rendering altogether.  I believe my app isn't well suited to it.  https://gist.github.com/jaunt/b5127af103995e80dd74ff14662a0281

**Comment by rudolfbyker** [comment]
That gist no longer exists, but I would love to see your solutions! I'm also working on a Vue app with PWA & pre-rendering.

**Comment by jaunt** [comment]
@rudolfbyker I've just finished a solution which ties in a gridsome generated static site into a vue-cli pwa app, so that they both become offline capable.  As soon as I get some time I'd love to make a starter-template and share it on github.

**Comment by Tofandel** [comment]
The app would still be offline capable without precaching the prerendered files (it's just prerendering after all)

But if you're still interested checkout [my plugin](https://www.npmjs.com/package/prerender-spa-plugin-next) it's prerender-spa-plugin but refactored for webpack 5 so the prerendered files are registered as asset correctly

**Comment by Tofandel** [comment]
Now available as `@prerender/webpack-plugin` needs a bit more documentation and tests

But I'll be closing this issue
