### ISSUE TITLE
Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by websanova** [JoshTheDerf/prerenderer#41]
I'm trying to change this timeout value but not having any luck.

I see in the docs here it says:

> Any additional options will be passed to page.goto(), such as timeout: 30000ms.

My config is quite simple and looks like this:

```
new Renderer({
    headless: true,
    timeout: 10000,
    renderAfterTime: 5000
})
```

That timeout just keeps showing the same error of

`Navigation Timeout Exceeded: 30000ms exceeded`

I'm using this plugin:

https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/package.json

Which does seem to have the latest version, so seems it should be ok.

How can I change this?

**Comment by Tofandel** [comment]
You're looking for the `navigationOptions`

```
navigationOptions: {
  timeout: 10000
}
```
