### ISSUE TITLE
Prerender detection

### ISSUE THREAD

**Issue by redxtech** [JoshTheDerf/prerenderer#50]
Hello! Is there any way for the app to tell whether it's being prerendered? I know that in `react-snap` you can check with `navigator.userAgent === 'ReactSnap'`, so I'm wondering if there's an equivalent for this prerenderer. Thanks :)

**Comment by rudolfbyker** [comment]
I see two options here:

- Look for `HeadlessChrome` in the default UserAgent value: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/85.0.4182.0 Safari/537.36`
- Launch puppeteer with the `--user-agent=asdf` arg. This will require changes in the `prerenderer` repo.

```js
const browser = await puppeteer.launch({
  args: ['--user-agent=hhh'],
});
```

**Comment by rudolfbyker** [comment]
It turns out, you can pass any command line arg for puppeteer like this:

```js
const prerenderer = new Prerenderer({
  // ...
  renderer: new PuppeteerRenderer({
    // ...
    args: ["--user-agent=moo"],
  }),
});
```

**Comment by Tofandel** [comment]
I'll just add a note that you can also use `'__PRERENDER_INJECTED' in window` which is set by default rather than the user agent
